spring:
  data:
    redis:
      ttl: 10

hash:
  threadPool:
    initialPoolSize: 5
    maxPoolSize: 10
  queue:
    capacity: 50
  batch:
    save: 100
    get: 200
  cache:
    capacity: 10
    fillPercent: 0.7
  cleaner:
    cron: "0 * * * * ?" #For test immediately

url:
  urlShort:
    baseUrl: "localhost:8088/v1/urls/"